# Generated by Django 3.0.8 on 2020-07-12 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0004_auto_20200711_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment_count',
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default='beast', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='meta_description',
            field=models.CharField(default='max_length is 200 characters', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='overview',
            field=models.CharField(default='max_length is 120 characters', max_length=120),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='max_length is 50 characters', max_length=50),
        ),
    ]
