# Generated by Django 3.0.8 on 2020-07-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(default='title', max_length=150),
        ),
    ]
