# Generated by Django 3.0.8 on 2020-07-15 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_news_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='meta_keywords',
            field=models.TextField(default='Enter the keywords like: word1, word2, word3,...'),
        ),
    ]
