# Generated by Django 3.0.8 on 2020-07-18 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_postview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostView',
        ),
    ]
